# Generated by Django 4.1.2 on 2022-11-24 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Performance_Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('signal', models.CharField(max_length=255)),
                ('close', models.CharField(max_length=255)),
            ],
        ),
    ]
