# Generated by Django 4.1.2 on 2022-11-24 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance_stock',
            name='close',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='performance_stock',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='performance_stock',
            name='signal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
