# Generated by Django 4.1.2 on 2022-11-25 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_alter_performance_stock_close_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='performance_stock',
            name='close',
        ),
        migrations.RemoveField(
            model_name='performance_stock',
            name='date',
        ),
        migrations.RemoveField(
            model_name='performance_stock',
            name='signal',
        ),
        migrations.AddField(
            model_name='performance_stock',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scanner.sector'),
        ),
    ]
